package com.nuwngc.think.nativeapp;

import android.app.*;import android.os.*;import android.content.*;import android.database.Cursor;import android.net.Uri;import android.provider.OpenableColumns;import android.view.*;import android.widget.*;import androidx.recyclerview.widget.*;import org.json.*;import io.socket.client.*;import java.io.*;import java.util.*;

public class ChatActivity extends Activity{
 int id;String title;RecyclerView list;EditText input;TextView typing;MsgAdapter ad;ArrayList<JSONObject> msgs=new ArrayList<>();Socket socket;Handler handler=new Handler(Looper.getMainLooper());long lastTyping=0;boolean connected=false;
 public void onCreate(Bundle b){super.onCreate(b);Api.init(this);setContentView(R.layout.activity_chat);id=getIntent().getIntExtra("id",0);title=getIntent().getStringExtra("title");((TextView)findViewById(R.id.title)).setText(title);typing=findViewById(R.id.typing);findViewById(R.id.back).setOnClickListener(v->finish());list=findViewById(R.id.messages);input=findViewById(R.id.input);ad=new MsgAdapter();list.setLayoutManager(new LinearLayoutManager(this));list.setAdapter(ad);findViewById(R.id.send).setOnClickListener(v->send(null));findViewById(R.id.photo).setOnClickListener(v->pickImage());input.setOnKeyListener((v,key,event)->false);input.addTextChangedListener(new android.text.TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int a){}public void onTextChanged(CharSequence s,int st,int b,int c){if(socket!=null&&socket.connected()&&System.currentTimeMillis()-lastTyping>1200){lastTyping=System.currentTimeMillis();try{socket.emit("typing",new JSONObject().putOpt("conversationId",id));}catch(Exception ignored){}}}public void afterTextChanged(android.text.Editable e){}});load();connect();}
 void load(){String c=Api.cached("messages_"+id);if(c!=null)try{JSONArray a=new JSONArray(c);msgs.clear();for(int i=0;i<a.length();i++)msgs.add(a.getJSONObject(i));ad.notifyDataSetChanged();scrollBottom();}catch(Exception ignored){}new Thread(()->{try{JSONObject j=Api.get("/api/conversations/"+id+"/messages?limit=100");JSONArray a=j.getJSONArray("messages");msgs.clear();for(int i=0;i<a.length();i++)msgs.add(a.getJSONObject(i));Api.cache("messages_"+id,a.toString());runOnUiThread(()->{ad.notifyDataSetChanged();scrollBottom();markRead();});}catch(Exception e){}}).start();}
 void scrollBottom(){if(msgs.size()>0)list.scrollToPosition(msgs.size()-1);}
 void markRead(){int last=msgs.size()>0?msgs.get(msgs.size()-1).optInt("id"):0;if(last==0)return;new Thread(()->{try{Api.post("/api/conversations/"+id+"/read",new JSONObject().put("messageId",last));}catch(Exception ignored){}}).start();}
 void send(String image){String s=input.getText().toString().trim();if(s.isEmpty()&&image==null)return;String client=UUID.randomUUID().toString();input.setText("");new Thread(()->{try{JSONObject body=new JSONObject().put("text",s).put("clientId",client);if(image!=null)body.put("image",image);JSONObject m=Api.post("/api/conversations/"+id+"/messages",body).getJSONObject("message");add(m);persist();}catch(Exception e){runOnUiThread(()->Toast.makeText(this,e.getMessage(),Toast.LENGTH_LONG).show());}}).start();}
 void add(JSONObject m){int mid=m.optInt("id");for(JSONObject x:msgs)if(x.optInt("id")==mid)return;msgs.add(m);runOnUiThread(()->{ad.notifyItemInserted(msgs.size()-1);scrollBottom();});}
 void persist(){JSONArray a=new JSONArray();for(JSONObject x:msgs)a.put(x);Api.cache("messages_"+id,a.toString());}
 void connect(){try{Map<String,List<String>> h=new HashMap<>();String sid=Api.cached("__dummy");String cookie=getSharedPreferences("thinkchat",0).getString("sid","");if(!cookie.isEmpty())h.put("Cookie",Collections.singletonList("sid="+cookie));IO.Options o=new IO.Options();o.transports=new String[]{"websocket"};o.extraHeaders=h;socket=IO.socket(Api.BASE,o);socket.on(Socket.EVENT_CONNECT,args->{connected=true;try{socket.emit("visibility",new JSONObject().put("visible",true));}catch(Exception ignored){}});socket.on(Socket.EVENT_CONNECT_ERROR,args->runOnUiThread(()->typing.setText("Kết nối realtime thất bại")));socket.on("message:new",args->{if(args.length>0&&args[0] instanceof JSONObject){JSONObject m=(JSONObject)args[0];if(m.optInt("conversationId")==id){add(m);persist();markRead();}}});socket.on("typing",args->{if(args.length>0&&args[0] instanceof JSONObject&&((JSONObject)args[0]).optInt("conversationId")==id)runOnUiThread(()->{typing.setText("đang nhập…");handler.removeCallbacksAndMessages("typing");handler.postAtTime(()->typing.setText(""),"typing",System.currentTimeMillis()+1800);});});socket.on("message:deleted",args->{if(args.length>0&&args[0] instanceof JSONObject){JSONObject e=(JSONObject)args[0];if(e.optInt("conversationId")==id){for(JSONObject m:msgs)if(m.optInt("id")==e.optInt("messageId")){try{m.put("deleted",true).put("text",JSONObject.NULL).put("image",JSONObject.NULL);}catch(Exception ignored){}}persist();runOnUiThread(()->ad.notifyDataSetChanged());}}});socket.on("session:ended",args->{Api.clearSession();runOnUiThread(()->{Toast.makeText(this,"Phiên đăng nhập đã kết thúc",Toast.LENGTH_LONG).show();startActivity(new Intent(this,LoginActivity.class));finish();});});socket.connect();}catch(Exception e){}}
 void pickImage(){Intent i=new Intent(Intent.ACTION_GET_CONTENT);i.setType("image/*");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,77);}
 protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r!=77||c!=RESULT_OK||d==null||d.getData()==null)return;Uri u=d.getData();new Thread(()->{try{byte[] b=readBytes(u);String mime=getContentResolver().getType(u);if(mime==null)mime="image/jpeg";if(b.length>10*1024*1024)throw new IOException("Ảnh tối đa 10 MB");String url=Api.uploadImage(b,mime);send(url);}catch(Exception e){runOnUiThread(()->Toast.makeText(this,e.getMessage(),Toast.LENGTH_LONG).show());}}).start();}
 byte[] readBytes(Uri u)throws Exception{InputStream in=getContentResolver().openInputStream(u);ByteArrayOutputStream out=new ByteArrayOutputStream();byte[] buf=new byte[8192];int n;while((n=in.read(buf))>0)out.write(buf,0,n);in.close();return out.toByteArray();}
 protected void onResume(){super.onResume();if(socket!=null&&socket.connected())try{socket.emit("visibility",new JSONObject().put("visible",true));}catch(Exception ignored){}}
 protected void onPause(){if(socket!=null&&socket.connected())try{socket.emit("visibility",new JSONObject().put("visible",false));}catch(Exception ignored){}super.onPause();}
 protected void onDestroy(){if(socket!=null)socket.disconnect();super.onDestroy();}
 class MsgAdapter extends RecyclerView.Adapter<MsgAdapter.V>{class V extends RecyclerView.ViewHolder{TextView s,t;V(View v){super(v);s=v.findViewById(R.id.sender);t=v.findViewById(R.id.text);}}
  public V onCreateViewHolder(ViewGroup p,int v){return new V(getLayoutInflater().inflate(R.layout.item_message,p,false));}
  public void onBindViewHolder(V h,int i){JSONObject x=msgs.get(i);int sid=x.optInt("senderId");boolean del=x.optBoolean("deleted");String text=x.optString("text","");String image=x.optString("image","");h.s.setText("#"+sid);h.t.setText(del?"Tin nhắn đã thu hồi":(!text.isEmpty()?text:(image.isEmpty()?"":"📷 Ảnh — chạm để mở")));h.itemView.setOnClickListener(v->{if(!image.isEmpty()&&!del){startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(Api.BASE+image)));}});h.itemView.setOnLongClickListener(v->{if(sid==currentUserId())showDelete(x);return true;});}
  public int getItemCount(){return msgs.size();}
 }
 int currentUserId(){try{String s=Api.cached("user_json");return s==null?-1:new JSONObject(s).optInt("id");}catch(Exception e){return -1;}}
 void showDelete(JSONObject m){new AlertDialog.Builder(this).setTitle("Thu hồi tin nhắn?").setMessage("Tin nhắn sẽ được gỡ cho mọi thành viên.").setNegativeButton("Hủy",null).setPositiveButton("Thu hồi",(d,w)->new Thread(()->{try{Api.delete("/api/messages/"+m.optInt("id"));m.put("deleted",true).put("text",JSONObject.NULL).put("image",JSONObject.NULL);persist();runOnUiThread(()->ad.notifyDataSetChanged());}catch(Exception e){runOnUiThread(()->Toast.makeText(this,e.getMessage(),Toast.LENGTH_SHORT).show());}}).start()).show();}
}
