package com.nuwngc.think.nativeapp;
import android.app.*;import android.os.*;import android.content.*;import android.view.*;import android.widget.*;import androidx.recyclerview.widget.*;import org.json.*;import java.util.*;
public class MainActivity extends Activity{
 RecyclerView list;ArrayList<JSONObject> data=new ArrayList<>();ConvAdapter ad;TextView status;
 public void onCreate(Bundle b){super.onCreate(b);Api.init(this);setContentView(R.layout.activity_main);list=findViewById(R.id.list);status=findViewById(R.id.status);list.setLayoutManager(new LinearLayoutManager(this));ad=new ConvAdapter();list.setAdapter(ad);findViewById(R.id.refresh).setOnClickListener(v->load(true));findViewById(R.id.profile).setOnClickListener(v->startActivity(new Intent(this,ProfileActivity.class)));load(false);}
 protected void onResume(){super.onResume();if(list!=null)load(false);}
 void load(boolean networkOnly){String c=Api.cached("conversations");if(!networkOnly&&c!=null)try{JSONArray a=new JSONArray(c);data.clear();for(int i=0;i<a.length();i++)data.add(a.getJSONObject(i));ad.notifyDataSetChanged();status.setText("Đã tải bản lưu · đang đồng bộ…");}catch(Exception ignored){}new Thread(()->{try{JSONArray a=Api.get("/api/conversations").getJSONArray("conversations");Api.cache("conversations",a.toString());data.clear();for(int i=0;i<a.length();i++)data.add(a.getJSONObject(i));runOnUiThread(()->{ad.notifyDataSetChanged();status.setText("Đã đồng bộ");});}catch(Api.ApiException e){if(e.code==401){Api.clearSession();runOnUiThread(()->{startActivity(new Intent(this,LoginActivity.class));finish();});}else runOnUiThread(()->status.setText(e.getMessage()));}catch(Exception e){runOnUiThread(()->status.setText("Ngoại tuyến · đang dùng dữ liệu đã lưu"));}}).start();}
 class ConvAdapter extends RecyclerView.Adapter<ConvAdapter.V>{class V extends RecyclerView.ViewHolder{TextView t,p,u;V(View v){super(v);t=v.findViewById(R.id.title);p=v.findViewById(R.id.preview);u=v.findViewById(R.id.unread);}}public V onCreateViewHolder(ViewGroup p,int v){return new V(getLayoutInflater().inflate(R.layout.item_conversation,p,false));}public void onBindViewHolder(V h,int i){JSONObject x=data.get(i);h.t.setText(x.optString("name",x.optString("type","Chat")));JSONObject m=x.optJSONObject("lastMessage");String preview=m==null?"Chưa có tin nhắn":(m.optBoolean("deleted")?"Tin nhắn đã thu hồi":(m.optString("text","").isEmpty()?(m.optString("image","").isEmpty()?"": "📷 Ảnh"):m.optString("text")));h.p.setText(preview);int unread=x.optInt("unread");h.u.setText(unread>0?String.valueOf(unread):"");h.itemView.setOnClickListener(v->{Intent in=new Intent(MainActivity.this,ChatActivity.class);in.putExtra("id",x.optInt("id"));in.putExtra("title",x.optString("name","Chat"));startActivity(in);});}public int getItemCount(){return data.size();}}
}
